apiVersion: v1
data:
  mapRoles: |
    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::727028628412:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1H7BOCK0NBMVY
      username: system:node:{{EC2PrivateDNSName}}
      - rolearn: arn:aws:iam::727028628412:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-31T13:33:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5167"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4bc62708-65ad-45b6-af31-b72470a812a5
